import type { Metadata } from "next";
import localFont from "next/font/local";

import type { ReactNode } from "react";

import { TRPCReactProvider } from "@/trpc/react";

import "../styles/globals.css";

const satoshiFont = localFont({
  src: "../../public/fonts/satoshi.ttf",
  variable: "--font-sans",
});

import { Instrument_Serif } from "next/font/google";

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  weight: "400",
});

export const metadata: Metadata = {
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  title: "Create T3 App",
};

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
  return (
    <html
      className={`${satoshiFont.variable} ${instrumentSerif.variable} antialiased`}
      lang="en"
    >
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
};

export default RootLayout;
