import type { Metadata } from "next";
import localFont from "next/font/local";

import type { ReactNode } from "react";

import { TRPCReactProvider } from "@/trpc/react";

import "../styles/globals.css";

const satoshiFont = localFont({
  src: "../../public/fonts/satoshi.ttf",
  variable: "--font-sans",
});

import { Geist, Geist_Mono, Instrument_Serif } from "next/font/google";

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  weight: "400",
});

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  title: "Create T3 App",
};

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
  return (
    <html
      className={`${satoshiFont.variable} ${instrumentSerif.variable} ${geist.variable} ${geistMono.variable} antialiased`}
      lang="en"
    >
      <body className="relative">
        <div
          className="pointer-events-none fixed inset-0 z-50 bg-repeat"
          style={{
            background: "url('/assets/grain.svg')",
          }}
        />
        <TRPCReactProvider>
          <div className="relative z-[0]">{children}</div>
        </TRPCReactProvider>
      </body>
    </html>
  );
};

export default RootLayout;
